var X0=48,XN=10,XS=36,EN3=.001,NHPI=-57.29578,HPI=57.29578,DIVPI2=2/Math.PI,DIRY=[0,1,0],PI=Math.PI,PI2=2*Math.PI,PData=function(){this.q=[0,0,0,0];this.a=[0,0,0];this.air=[0,0];this.onDataZ=this.onDataL=null;this.pressed=!1;this.battery=0;this.rssi=-128;this.rssi10=0;this.mac="";this.dataConnected=!1;this.quaternion=quat.create();this.doQuat=!1;this.ray=vec3.create();this.doRay=!1;this.rayCache=vec3.create();this.handZ=this.angleY=0;this.doHandZ=!1;this.deltaY=0;DIRY=vec3.fromValues(0,1,0);this.deltaZ=
this.zCache=this.pressdTime=0;this.checkRZ=this.checkFB=this.checkLR=this.checkTD=this.doMouse=this.doDeltaZ=!1;this.wayCheckTD=new WayCheck;this.wayCheckTD.mpl=1;this.wayCheckLR=new WayCheck;this.wayCheckRZ=new WayCheck;this.wayZ=0};
PData.prototype.parse=function(a){this.dataConnected=!0;var b=a[2];1==b?25>a.length||(this.q[0]=toInt(a[4],a[5]),this.q[1]=toInt(a[7],a[8]),this.q[2]=toInt(a[10],a[11]),this.q[3]=toInt(a[13],a[14]),this.a[0]=toInt(a[16],a[17])*EN3,this.a[1]=toInt(a[19],a[20])*EN3,this.a[2]=toInt(a[22],a[23])*EN3,this.doMouse=this.doDeltaZ=this.doHandZ=this.doRay=this.doQuat=!1,this.checkRZ&&(this.getDeltaZ(),this.wayCheckRZ.update(this.deltaZ)),this.checkTD&&(a=180*this.ray[2],this.updateQuat(),this.updateRay(),this.wayCheckTD.update(deltaAngle(a,
180*this.ray[2]))),this.checkLR&&(this.getMouse(0),this.wayCheckLR.update(180*this.deltaY)),this.checkFB&&(a=this.a[1],this.wayZ=.1<a?1:-.1>a?-1:0),this.onDataL&&(a=vec3.length(this.a),this.onDataL(a)),this.onDataZ&&(this.getDeltaZ(),this.onDataZ(this.deltaZ))):2==b?(this.pressed=!0,this.pressdTime=Date.now()):3==b?7>a.Length||(this.battery=a[4],this.rssi=toRssi(a[5]),this.rssi10=rssiTo10(this.rssi)):4==b?(this.dataConnected=!1,this.rssi=-128,this.rssi10=0):5!=b||37>a.Length||(this.battery=a[5],this.rssi=
toRssi(a[6]),this.rssi10=rssiTo10(this.rssi),this.mac=ToMac(a,9))};PData.prototype.isPressed=function(){var a=this.pressed;this.pressed=!1;return 300<Date.now()-this.pressdTime?!1:a};PData.prototype.vibrate=function(a,b,c){b+=X0;c+=X0;b=new Uint8Array([XS,97,X0,b,c,XN,XN,XN,XN]);a.send(b.buffer)};PData.prototype.ledOn=function(a,b,c){this.ledOffAll(a,b);sendLedOn(a,b,c,300)};
PData.prototype.ledOffAll=function(a,b){var c=0;0!=b&&(sendLedOff(a,0,0),c+=150);1!=b&&(sendLedOff(a,1,c),c+=150);2!=b&&sendLedOff(a,2,c)};PData.prototype.ledFlash=function(a,b,c,d,e){this.ledOffAll(a,b);b+=X0;e+=X0;c+=X0;d+=X0;b=new Uint8Array([XS,102,X0,b,c,d,e,XN,XN,XN,XN]);delaySend(a,b.buffer,300)};PData.prototype.ledOnPro=function(a,b,c,d){0==b?sendLedOff(a,0,0):sendLedOn(a,0,b,0);0==c?sendLedOff(a,1,150):sendLedOn(a,1,c,150);0==d?sendLedOff(a,2,300):sendLedOn(a,2,d,300)};
function sendLedOn(a,b,c,d){b+=X0;c+=X0;b=new Uint8Array([XS,100,X0,b,c,XN,XN,XN,XN]);delaySend(a,b.buffer,d)}function sendLedOff(a,b,c){b+=X0;b=new Uint8Array([XS,101,X0,b,XN,XN,XN,XN]);delaySend(a,b.buffer,c)}function delaySend(a,b,c){0==c?a.send(b):setTimeout(function(){a.send(b)},c)}PData.prototype.getMac=function(a){var b=new Uint8Array([XS,119,XN,XN,XN,XN]);a.send(b.buffer)};PData.prototype.getHandZ=function(){this.updateHandZ();return this.handZ};
PData.prototype.updateHandZ=function(){this.doHandZ||(this.handZ=toHandZ(this.q[0],this.q[1],this.q[2],this.q[3]),this.doHandZ=!0)};function toHandZ(a,b,c,d){mag=Math.sqrt(a*a+b*b+c*c+d*d);mag=1E-6<=mag?1/mag:1E6;qW2=a*mag;qX2=b*mag;qY2=c*mag;qZ2=d*mag;ez=Math.atan2(2*(qX2*qZ2-qW2*qY2),1-2*(qX2*qX2+qY2*qY2))*NHPI;ez+=5;180<ez&&(ez-=360);return ez}
PData.prototype.getDeltaZ=function(){if(this.doDeltaZ)return this.deltaZ;this.updateHandZ();this.deltaZ=deltaAngle(this.zCache,this.handZ);this.zCache=this.handZ;this.doDeltaZ=!0;return this.deltaZ};
PData.prototype.getMouse=function(a){if(this.doMouse)return this.air[a];this.updateQuat();this.updateRay();this.air[1]=Math.tan(Math.atan2(this.ray[2],1));vec3.set(this.rayCache,this.ray[0],Math.tan(Math.atan2(this.ray[1],1)),0);var b=vec3.angle(DIRY,this.rayCache);0>this.ray[0]&&(b*=-1);this.deltaY=deltaRadians(this.angleY,b)*DIVPI2;this.angleY=b;this.air[0]=clamp(this.air[0]+this.deltaY,-1,1);this.doMouse=!0;return this.air[a]};
PData.prototype.updateQuat=function(){this.doQuat||(quat.set(this.quaternion,this.q[1],this.q[2],this.q[3],this.q[0]),quat.normalize(this.quaternion,this.quaternion),this.doQuat=!0)};PData.prototype.updateRay=function(){this.doRay||(vec3.transformQuat(this.ray,DIRY,this.quaternion),this.doRay=!0)};function deltaAngle(a,b){num=repeat(b-a,360);180<num&&(num-=360);return num}function deltaRadians(a,b){num=repeat(b-a,PI2);num>PI&&(num-=PI2);return num}
function repeat(a,b){return clamp(a-Math.floor(a/b)*b,0,b)}function clamp(a,b,c){return Math.max(b,Math.min(c,a))}function toInt(a,b){var c=(b&255)<<8|a&255;32767<c&&(c-=65536);return c}function toRssi(a){a-=256;-128>a&&(a=-128);return a}function rssiTo10(a){a+=128;return 0==a?0:10>a?1:85<a?10:a=Math.round(a/9)}function ToMac(a,b){for(var c="",d=b+6,e=b;e<d;e++)c+=a[e].toString(16).toUpperCase();return c}
var ShakeGesture=function(){this.triggerForce=1;this.lockTime=.3;this.magnitude=this.accPower=this.instantForce=0;this.triggerFlag=!1;this.lastForce=0;this.onTrigger=null;this.pauseUpdate=this.run=!1;this.pauseTimer=null;this.powerCount=0};ShakeGesture.prototype.pauseUpdateData=function(a){this.pauseTimer&&(clearTimeout(this.pauseTimer),this.pauseTimer=null);this.pauseUpdate=!0;var b=this;this.pauseTimer=setTimeout(function(){b.pauseUpdateDataEnd()},a)};
ShakeGesture.prototype.pauseUpdateDataEnd=function(){this.pauseUpdate=!1};ShakeGesture.prototype.updateS=function(a){this.run&&!this.pauseUpdate&&(this.lastForce=this.magnitude,this.magnitude=a,this.magnitude>this.accPower?(this.accPower=this.magnitude,this.powerCount=0):(this.powerCount++,3<this.powerCount&&(this.powerCount=this.accPower=0)))};
ShakeGesture.prototype.isPowerGreater=function(a,b,c){this.run=!0;if(this.accPower>=a){if(0<this.deltaForce&&Math.abs(this.magnitude-this.lastForce)<this.deltaForce)return!1;this.pauseUpdateData(parseInt(1E3*c));this.accPower=0;return!0}return!1};ShakeGesture.prototype.pauseUpdateS=function(a){this.pauseUpdateData(1E3*a);this.accPower=0};ShakeGesture.prototype.getForce=function(){this.run=!0;return this.accPower};
var WayCheck=function(){this.way=this.v0=0;this.min=.1;this.max=.4;this.mpl=.5;this.res=0};WayCheck.prototype.update=function(a){var b=a-this.v0;this.v0=a;a=0;b>this.min?a=1:b<-this.min&&(a=-1);this.way+=a*this.mpl;1<this.way?this.way=1:-1>this.way&&(this.way=-1);this.res=this.way>this.max?1:this.way<-this.max?-1:0};WayCheck.prototype.getWay=function(){return this.res};var Smoother=function(){this.res=this.cache=0};
Smoother.prototype.lerp=function(a,b){if(0==b)return a;this.res=lerp(a,this.cache,b);this.cache=a;return this.res};Smoother.prototype.smooth=function(a){this.res=lerp(a,this.cache,.5);this.cache=a;return this.res};Smoother.prototype.smoothAngle=function(a){this.res=lerpAngle(a,this.cache,.5);this.cache=a;return this.res};function lerp(a,b,c){return a+(b-a)*clamp01(c)}function lerpAngle(a,b,c){b=repeat(b-a,360);180<b&&(b-=360);return a+b*clamp01(c)}function clamp01(a){return 0>a?0:1<a?1:a};